
#ifndef _WIFI_SetFunctionData_H_
#define _WIFI_SetFunctionData_H_

typedef enum
{
    WIFI_FUNC_0001_POWER_SEL = 0x0001,
    WIFI_FUNC_0002_COLD_SEL,    // 냉수설정
    WIFI_FUNC_0003_HOT_LOCK_SEL,// 온수잠금설정
    WIFI_FUNC_0004_SAVE_SEL,    // 절전설정
    WIFI_FUNC_0005_LOCK_SEL,    // 잠금설정
    WIFI_FUNC_0006_MUTE_SEL,    // 무음설정
    WIFI_FUNC_0007_STERILIZE_SEL,   // 살균설정
    WIFI_FUNC_0008_ICE_SEL,     // 제빙설정
    WIFI_FUNC_0009_HOT_TEMP,    // 온수온도표시
    WIFI_FUNC_000A_COLD_TEMP,   // 냉수온도표시
    WIFI_FUNC_000B_WATER_SEL,   // 물 선택
    WIFI_FUNC_000C_USER_SEL,    // 사용자
    WIFI_FUNC_000D_WATER_OUTQUANTITY,// 추출물량
    WIFI_FUNC_000E_TIME_YEAR,       // 현재시간 연
    WIFI_FUNC_000F_TIME_MONTHDAY,   // 현재시간 월일
    WIFI_FUNC_0010_TIME_MINSEC,     // 현재시간 시분
    WIFI_FUNC_0011_STERILIZE_CYCLE, // 살균주기
    WIFI_FUNC_0012_STERILIZE_MODE,  // 살균주기모드
    WIFI_FUNC_0013_STERILIZE_TIME,  // 살균시간설정
    WIFI_FUNC_0014_STERILIZE_STATUS, // 살균동작상태
    WIFI_FUNC_0015_TDS_IN,  // 입수 TDS
    WIFI_FUNC_0016_TDS_OUT, // 출수 TDS
    WIFI_FUNC_0017_WATER_PRESSURE,  // 폐 수압
    WIFI_FUNC_0018_TDS_INTEMP,  // TDS 입수온도
    WIFI_FUNC_0019_TDS_OUTTEMP, // TDS 출수온도
    WIFI_FUNC_001A_HOT_INTEMP,  // 순간온수 원수온도
    WIFI_FUNC_001B_HOT_MEANTEMP,// 순간온수 평균온도
    WIFI_FUNC_001C_HOT_SELTEMP, // 순간온수 설정온도
    WIFI_FUNC_001D_WATER_INQUANTITY,// 입수유량
    WIFI_FUNC_001E_AUTODRAIN_SEL,   // 자동배수 설정
    WIFI_FUNC_001F_DRAIN_STATUS,     // 배수동작
    WIFI_FUNC_0020_WATER_REQUANTITY,// 재 정수 유량
    WIFI_FUNC_0021_HEART_TIME1, // 하트서비스시간
    WIFI_FUNC_0022_HEART_TIME2, //
    WIFI_FUNC_0023_HEART_TIME3, //
    WIFI_FUNC_0024_HEART_TIME4, //
    WIFI_FUNC_0025_FILTER_NOTICE1,  // 필터교환알림
    WIFI_FUNC_0026_FILTER_NOTICE2,
    WIFI_FUNC_0027_FILTER_NOTICE3,
    WIFI_FUNC_0028_FILTER_NOTICE4,
    WIFI_FUNC_0029_SERVICE_TIME,    // 서비스 경과일
    WIFI_FUNC_002A_REMOVE_STATE,    // 제거율 상태
    WIFI_FUNC_002B_SAVE_DETECT,     // 절전진입X
    WIFI_FUNC_002C_SILVER_CARE,     // 실버케어
    WIFI_FUNC_002D_DRAIN_QUANTITY,  // 배수물량
    WIFI_FUNC_002E_STERILIZE_QUANTITY,  // 살균물량
    WIFI_FUNC_002F_SPARKLING_SEL,   // 탄산수 선택
    WIFI_FUNC_0030_ICE_MAKETIME,    // 얼음추출시간
    WIFI_FUNC_0031_VOICE_SEL,   // 음성안내설정
    WIFI_FUNC_0032_ICELOCK_SEL, // 얼음잠금 설정
    WIFI_FUNC_0033_VOICE_VOL_SEL,    // 음성볼륨 설정
    WIFI_FUNC_0034_LIGHT_SEL,   // 조명설정
    WIFI_FUNC_0035_COVER1_OPEN, // 커버1 열림
    WIFI_FUNC_0036_COVER2_OPEN, // 커버2 열림
    WIFI_FUNC_0037_SLEEP_SEL,  // 슬립모드 선택
    WIFI_FUNC_0038_MASH_CLEAN,  // 매쉬망 청소알람
    WIFI_FUNC_0039_HOT_SEL,     // 온수설정
    WIFI_FUNC_003A_FREEZE_BURST,
    WIFI_FUNC_003B_HOT_TEMP_SEL,    // 나의 온수온도 설정
    WIFI_FUNC_003C_COLD_STRENGTH_SEL,   // 냉수 강약조절
    WIFI_FUNC_003D_HEIGHT_SEL,          // 고도모드
    WIFI_FUNC_003E_WATER_COURSE_STATUS, // 유로모듈 장착상태
    WIFI_FUNC_003F_WATER_COURSE_RESET,  // 유로모듈 리셋
    WIFI_FUNC_0040_SMART_CHECK_RQST,    // 스마트 고장진단 설정
    WIFI_FUNC_0041_SMART_CHECK_STATUS,  // 스마트 고장진단 상태
    WIFI_FUNC_0042_SMART_CHECK_PROGRESS,// 스마트 고장진단 진행률
    WIFI_FUNC_0043_FILTER_STATUS1,      // 필터 장착상태
    WIFI_FUNC_0044_FILTER_STATUS2,
    WIFI_FUNC_0045_FILTER_STATUS3,
    WIFI_FUNC_0046_FILTER_STATUS4,
    WIFI_FUNC_0047_WATER_QUANTITY_SEL,  // 물량 선택
    WIFI_FUNC_0048_HOT_TEMP_SEL,
    WIFI_FUNC_0049_OUT_BUTTON_LIGHT,
    WIFI_FUNC_004A_WELCOME_LIGHT,
    WIFI_FUNC_004B_HIDDEN_LCD_SEL,
    WIFI_FUNC_004C_FAUCET_MOVE_SEL,
    WIFI_FUNC_004D_FAUCET_MOVE_STATUS,
    WIFI_FUNC_004E_CUP_SENSING_SEL,
    WIFI_FUNC_004F_SOUND_VOL_SEL,
    WIFI_FUNC_0050_UV_STERILIZE_STATUS,
    WIFI_FUNC_0051_QUANTITY_USE_SEL,
    WIFI_FUNC_0052_VOICE_MODE_SEL,
    WIFI_FUNC_0053_FILTER_RESET1,
    WIFI_FUNC_0054_FILTER_RESET2,
    WIFI_FUNC_0055_FILTER_RESET3,
    WIFI_FUNC_0056_FILTER_RESET4,
    WIFI_FUNC_0057_CUP_SENSING_SENSITIVITY,
    WIFI_FUNC_0058_ICE_SIZE_SEL,
    WIFI_FUNC_0059_ICE_ONOFF_SEL,
    WIFI_FUNC_005A_UV_ICE_TANK_STATUS,
    WIFI_FUNC_005B_UV_ICE_TRAY_STATUS,
    WIFI_FUNC_005C_SMART_CHECK_RESULT,
    WIFI_FUNC_005D_UV_ICE_FAUCET_STATUS,
    WIFI_FUNC_005E_SLEEP_MODE_SEL,
    WIFI_FUNC_005F_SLEEP_START_HOUR,
    WIFI_FUNC_0060_SLEEP_START_MIN,
    WIFI_FUNC_0061_SLEEP_END_HOUR,
    WIFI_FUNC_0062_SLEEP_END_MIN,
    
    WIFI_FUNC_NUM
}E_API_A1010_T;

void* GetWifiFuncEventList ( void );
U16 GetWifiFuncListSize ( void );

U8 IsExceptId ( U16 mId );


#endif


